server:
  port: 9092

spring:
  application:
    name: demo2

eureka:
  instance:
    appname: demo2
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
