server:
  port: 9091

spring:
  application:
    name: demo1

eureka:
  instance:
    appname: demo1
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
